ALTER TABLE "Task"
ADD COLUMN "levelingDelayDays" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "BaselineTaskSnapshot"
ADD COLUMN "workHours" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "plannedCost" DECIMAL(12, 2) NOT NULL DEFAULT 0;
